anewstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/<int:page>/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('product/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name']),]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .models import Category, Product
from django.core.paginator import Paginator


def product_list(request, category_slug=None, page=1):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 3)
    current_page = paginator.page(int(page))
    slag_url = category_slug

    return render(request, 'shop/list.html', {'category': category, 'categories': categories, 'products': current_page, 'slug_url': slag_url})


def product_detail(request, product_slug):
    product = Product.objects.get(slug=product_slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/detail.html', {'product': product, 'cart_product_form': cart_product_form})

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<title>{% block title %}My shop{% endblock %}</title>

<meta name="keywords" content="web store, free templates, website templates, CSS, HTML" />
<meta name="description" content="Web Store Theme - free CSS template provided by templatemo.com" />
<link href="{% static 'shop/css/templatemo_style.css' %}" rel="stylesheet" type="text/css" />

<link rel="stylesheet" type="text/css" href="{% static 'shop/css/ddsmoothmenu.css' %}" />

<script type="text/javascript" src="{% static 'shop/js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'shop/js/ddsmoothmenu.js' %}">

/***********************************************
* Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/
</script>

<script type="text/javascript">

ddsmoothmenu.init({
	mainmenuid: "templatemo_menu", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

</script>

<link rel="stylesheet" type="text/css" href="{% static 'shop/css/styles.css' %}" />
<script language="javascript" type="text/javascript" src="{% static 'shop/scripts/mootools-1.2.1-core.js' %}"></script>
<script language="javascript" type="text/javascript" src="{% static 'shop/scripts/mootools-1.2-more.js' %}"></script>
<script language="javascript" type="text/javascript" src="{% static 'shop/scripts/slideitmoo-1.1.js' %}"></script>
<script language="javascript" type="text/javascript">
	window.addEvents({
		'domready': function(){
			/* thumbnails example , div containers */
			new SlideItMoo({
						overallContainer: 'SlideItMoo_outer',
						elementScrolled: 'SlideItMoo_inner',
						thumbsContainer: 'SlideItMoo_items',
						itemsVisible: 5,
						elemsSlide: 2,
						duration: 200,
						itemsSelector: '.SlideItMoo_element',
						itemWidth: 171,
						showControls:1});
		},

	});

	function clearText(field)
	{
		if (field.defaultValue == field.value) field.value = '';
		else if (field.value == '') field.value = field.defaultValue;
	}
</script>

</head>

<body id="home">

    <div id="templatemo_wrapper">
        <div id="templatemo_header">
            <div id="site_title"><h1><a>Мій сайт</a></h1></div>

            <div id="header_right">
                <ul id="language">
                    <li><a><img src="{% static 'shop/images/usa.png' %}" alt="English" /></a></li>
                    <li><a><img src="{% static 'shop/images/Ukraine.png' %}" width="32" alt="Ukraine" /></a></li>
                </ul>
                <div class="cleaner"></div>
                <div id="templatemo_search">
                    <form action="#" method="get">
                      <input type="text" value="Search" name="keyword" id="keyword" title="keyword" onfocus="clearText(this)" onblur="clearText(this)" class="txt_field" />
                      <input type="submit" name="Search" value="" alt="Search" id="searchbutton" title="Search" class="sub_btn"  />
                    </form>
                </div>
             </div> <!-- END -->
        </div> <!-- END of header -->

            <div id="templatemo_menu" class="ddsmoothmenu">
            <ul>
                <li><a href="{% url 'shop:product_list' %}" class="selected">Головна</a></li>
                <li><a href="{% url 'cart:cart_detail' %}">Кошик</a></li>
                <li><a href="about">Увійти</a></li>
                <li><a href="faqs">Мій профіль</a>
                    <ul>
                        <li><a href="#">Кошик</a></li>
                        <li><a href="#">Особистий кабінет</a></li>
                        <li><a href="#">Адмін панель</a></li>
                        <li><a href="#">Вийти</a></li>
                    </ul>
                </li>
                <li><a href="checkout">Checkout</a></li>
                <li><a href="contact">Contact</a></li>
            </ul>
            <br style="clear: left" />
        </div> <!-- end of templatemo_menu -->

    <div id="templatemo_middle">
    	<img src="{% static 'shop/images/templatemo_image_01.png' %}" alt="Image 01" style="width: 250px;" />
    	<h1>Introducing Web Store</h1>
        <p><a href="http://www.templatemo.com" target="_parent">Web Store</a> is a free css template for your personal or commercial websites. Feel free to download, edit and use this template for any purpose.</p>
        <a href="#" class="buy_now">Browse All Products</a>
    </div> <!-- END of middle -->

        {% block categories %}

        {% endblock %}

              <div class="cart">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            Ваш кошик:
            <a href="{% url 'cart:cart_detail' %}">
              {{ total_items }} товар {{ total_items|pluralize }},
              ${{ cart.get_total_price }}
            </a>
          {% elif not order %}
            Ваш кошик порожній.
          {% endif %}
        {% endwith %}
      </div>

        {% block content %}

        {% endblock %}

        <div id="templatemo_footer">

            <div class="col col_16">
                <h4>Категорії</h4>
                <ul class="footer_menu">
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url 'shop:product_list' %}">Всі категорії</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %} class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
            </div>
            <div class="col col_16">
                <h4>Pages</h4>
                <ul class="footer_menu">
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Products</a></li>
                    <li><a href="#">Shipping</a></li>
                    <li><a href="#">Privacy</a></li>
                </ul>
            </div>
            <div class="col col_16">
                <h4>Partners</h4>
                <ul class="footer_menu">
                    <li><a href="http://www.flashmo.com/">Free Flash Templates</a></li>
                    <li><a href="http://www.templatemo.com/">Free CSS Templates</a></li>
                    <li><a href="http://www.koflash.com/">Website Gallery</a></li>
                    <li><a href="http://www.webdesignmo.com/blog/">Web Design Resources</a></li>
                </ul>
            </div>
            <div class="col col_16">
                <h4>Social</h4>
                <ul class="footer_menu">
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Youtube</a></li>
                    <li><a href="#">LinkedIn</a></li>
              </ul>
            </div>
            <div class="col col_13 no_margin_right">
                <h4>About Us</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur semper quam sit amet turpis rhoncus id venenatis tellus sollicitudin. Fusce ullamcorper, dolor non mollis pulvinar, turpis tortor commodo nisl. Validate <a href="http://validator.w3.org/check?uri=referer" rel="nofollow"><strong>XHTML</strong></a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer" rel="nofollow"><strong>CSS</strong></a>.</p>
            </div>


        </div> <!-- END of footer -->
        <div class="cleaner h40"></div>
            <center>
                Copyright © 2048 Your Company Name | Designed by <a href="http://www.templatemo.com" target="_parent">Free CSS Templates</a>
            </center>
    </div>

</body>
</html>

shop/templates/shop/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'shop/css/base.css' %}" />
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="width: 300px;" >
        <h4>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h4>
    <h2>{{ product.name }}</h2>
    <p class="price">{{ product.price }} Грн</p>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>
    {{ product.description|linebreaks }}
  </div>
{% endblock %}

shop/templates/shop/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block categories %}
    <div id="templatemo_main_top"></div>
        <div id="templatemo_main">
            <div id="product_slider">
                <div id="SlideItMoo_outer">
                    <div id="SlideItMoo_inner">
                        <div id="SlideItMoo_items">
                            <div class="SlideItMoo_element">
                                    <a href="http://www.templatemo.com/page/1" target="_parent">
                                    <img src="{% static 'shop/images/gallery/01.jpg' %}" height="150" width="200" alt="product 1" /></a>
                            </div>
                            <div class="SlideItMoo_element">
                                    <a href="http://www.templatemo.com/page/2" target="_parent">
                                    <img src="{% static 'shop/images/gallery/02.jpg' %}" height="150" width="200" alt="product 2' %}" /></a>
                            </div>
                            <div class="SlideItMoo_element">
                                    <a href="http://www.templatemo.com/page/3" target="_parent">
                                     <img src="{% static 'shop/images/gallery/03.jpg' %}" height="150" width="200" alt="product 3" /></a>
                            </div>
                            <div class="SlideItMoo_element">
                                    <a href="http://www.templatemo.com/page/4" target="_parent">
                                    <img src="{% static 'shop/images/gallery/04.jpg' %}" height="150" width="200" alt="product 4" /></a>
                            </div>
                            <div class="SlideItMoo_element">
                                    <a href="http://www.templatemo.com/page/5" target="_parent">
                                   <img src="{% static 'shop/images/gallery/05.jpg' %}" height="150" width="200" alt="product 5" /></a>
                            </div>
                            <div class="SlideItMoo_element">
                                    <a href="http://www.templatemo.com/page/6" target="_parent">
                                    <img src="{% static 'shop/images/gallery/06.jpg' %}" height="150" width="200" alt="product 6" /></a>
                            </div>
                            <div class="SlideItMoo_element">
                                    <a href="http://www.templatemo.com/page/6" target="_parent">
                                    <img src="{% static 'shop/images/gallery/07.jpg' %}" height="150" width="200" alt="product 7" /></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="cleaner"></div>
            </div>

  <div id="sidebar">
    <h3>Categories</h3>
    <ul class="sidebar_menu">
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url 'shop:product_list' %}">Всі категорії</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>

<!--                <h3>Newsletter</h3>-->
<!--                <p>Praesent aliquam mi id tellus pretium pulvinar in vel ligula.</p>-->
<!--                <div id="newsletter">-->
<!--                    <form action="#" method="get">-->
<!--                      <input type="text" value="Subscribe" name="email_newsletter" id="email_newsletter" title="email_newsletter" onfocus="clearText(this)" onblur="clearText(this)" class="txt_field" />-->
<!--                      <input type="submit" name="subscribe" value="Subscribe" alt="Subscribe" id="subscribebtn" title="Subscribe" class="subscribebtn"  />-->
<!--                    </form>-->
<!--                    <div class="cleaner"></div>-->
<!--                </div>-->
  </div> <!-- END of sidebar -->
{% endblock %}

{% block content %}
 <div id="content">
   {% for product in products %}
        	<div class="col col_14 product_gallery">
              <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" style="width: 205px;">
              </a>
                <h3>{{ product.name }}</h3>
                <p class="product_price">{{ product.price }}</p>
                <a href="{% url 'cart:cart_detail' %}" class="add_to_cart">Додати в кошик</a>
            </div>
   {% endfor %}

<div class="Paginator">
  <ul class="pagination justify-content-center">
    <li class="page-item disabled">
      <a class="page-link" href="#" tabindex="-1">Previous</a>
    </li>
      {% for page in products.paginator.page_range %}
    <li class="page-item"><a class="page-link" href="{% url 'shop:product_list' slug_url page %}">{{ page }}</a></li>
        {% endfor %}
    <li class="page-item">
      <a class="page-link" href="#">Next</a>
    </li>
  </ul>
</div>

  </div>
{% endblock %}